export const seedCities = [
  // --- RAJASTHAN ---
  {
    name: 'Jaipur',
    country: 'India',
    region: 'Rajasthan',
    description: 'The Pink City featuring majestic Amer Fort, Hawa Mahal, opulent palaces, astronomical Jantar Mantar, and bustling bazaars.',
    costIndex: 'Moderate',
    popularity: 98,
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 26.9124, lng: 75.7873 },
  },
  {
    name: 'Goa',
    country: 'India',
    region: 'Goa',
    description: 'Sun-drenched beaches, Portuguese heritage churches, lively beach shacks, Dudhsagar waterfalls, and thrilling water sports.',
    costIndex: 'Moderate',
    popularity: 94,
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 15.2993, lng: 74.124 },
  },
  {
    name: 'Manali',
    country: 'India',
    region: 'Himachal Pradesh',
    description: 'High-altitude Himalayan paradise surrounded by pine forests, snow peaks, Solang Valley adventures, and Rohtang Pass.',
    costIndex: 'Moderate',
    popularity: 89,
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 32.2432, lng: 77.1892 },
  },
  {
    name: 'Udaipur',
    country: 'India',
    region: 'Rajasthan',
    description: 'The City of Lakes, known for fairytale palaces, shimmering Lake Pichola, and royal Rajput heritage.',
    costIndex: 'Moderate',
    popularity: 85,
    image: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 24.5854, lng: 73.7125 },
  },
  {
    name: 'Varanasi',
    country: 'India',
    region: 'Uttar Pradesh',
    description: 'The spiritual heart of India on the banks of Holy River Ganga, world-famous for sacred Ghats and mesmerizing evening Aarti.',
    costIndex: 'Budget',
    popularity: 82,
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 25.3176, lng: 82.9739 },
  },
  {
    name: 'Munnar & Kochi',
    country: 'India',
    region: 'Kerala',
    description: 'Rolling emerald tea plantations in misty Munnar paired with historic Fort Kochi spice markets and Chinese fishing nets.',
    costIndex: 'Moderate',
    popularity: 79,
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 10.0889, lng: 77.0595 },
  },
  {
    name: 'Leh Ladakh',
    country: 'India',
    region: 'Ladakh',
    description: 'Land of High Passes with sapphire Pangong Tso, Nubra Valley sand dunes, ancient Tibetan monasteries, and Khardung La.',
    costIndex: 'Luxury',
    popularity: 76,
    image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 34.1526, lng: 77.5771 },
  },
  {
    name: 'Agra',
    country: 'India',
    region: 'Uttar Pradesh',
    description: 'Home to the eternal Taj Mahal, a Wonder of the World, along with Agra Fort and Mughal architectural masterpieces.',
    costIndex: 'Moderate',
    popularity: 74,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 27.1767, lng: 78.0081 },
  },
  {
    name: 'Hampi',
    country: 'India',
    region: 'Karnataka',
    description: 'Breathtaking UNESCO World Heritage boulder landscape with ruins of the 14th-century Vijayanagara Empire.',
    costIndex: 'Budget',
    popularity: 71,
    image: 'https://images.unsplash.com/photo-1600100397608-f010f4439c71?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 15.335, lng: 76.46 },
  },
  {
    name: 'Kolkata',
    country: 'India',
    region: 'West Bengal',
    description: 'The cultural and literary capital of India, famous for Victoria Memorial, Howrah Bridge, trams, and rich sweets.',
    costIndex: 'Budget',
    popularity: 68,
    image: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 22.5726, lng: 88.3639 },
  },
  {
    name: 'Jodhpur',
    country: 'India',
    region: 'Rajasthan',
    description: 'The Sun City and Blue City guarded by the colossal Mehrangarh Fort rising above vibrant indigo houses.',
    costIndex: 'Moderate',
    popularity: 67,
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 26.2389, lng: 73.0243 },
  },
  {
    name: 'Jaisalmer',
    country: 'India',
    region: 'Rajasthan',
    description: 'The Golden City nestled in the heart of the Thar Desert, famed for yellow sandstone living fort and camel safaris.',
    costIndex: 'Moderate',
    popularity: 65,
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 26.9157, lng: 70.9083 },
  },
  {
    name: 'Ahmedabad',
    country: 'India',
    region: 'Gujarat',
    description: 'India\'s first UNESCO World Heritage City, famous for intricate pols, Sabarmati Gandhi Ashram, and vibrant culinary feasts.',
    costIndex: 'Budget',
    popularity: 64,
    image: 'https://images.unsplash.com/photo-1609137144820-ea04e6c1e345?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 23.0225, lng: 72.5714 },
  },
  {
    name: 'Rann of Kutch',
    country: 'India',
    region: 'Gujarat',
    description: 'The spectacular Great White Salt Desert, world-renowned for moonlight festivals, handicraft villages, and flamingos.',
    costIndex: 'Moderate',
    popularity: 63,
    image: 'https://images.unsplash.com/photo-1583249598754-b7a2d4880a6b?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 23.8344, lng: 69.8329 },
  },
  {
    name: 'Mumbai',
    country: 'India',
    region: 'Maharashtra',
    description: 'The bustling City of Dreams with iconic Marine Drive, colonial Gateway of India, Bollywood, and legendary street food.',
    costIndex: 'Luxury',
    popularity: 92,
    image: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 19.076, lng: 72.8777 },
  },
  {
    name: 'Pune',
    country: 'India',
    region: 'Maharashtra',
    description: 'Cultural capital of Maharashtra, historic seat of the Maratha Empire with forts, universities, and pleasant hill weather.',
    costIndex: 'Budget',
    popularity: 62,
    image: 'https://images.unsplash.com/photo-1627894483216-2138af692e32?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 18.5204, lng: 73.8567 },
  },
  {
    name: 'Gokarna',
    country: 'India',
    region: 'Karnataka',
    description: 'Pristine tranquil beaches like Om Beach and Kudle Beach, surrounded by sacred coastal temples and hiking trails.',
    costIndex: 'Budget',
    popularity: 61,
    image: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 14.5479, lng: 74.3188 },
  },
  {
    name: 'Delhi',
    country: 'India',
    region: 'National Capital Territory',
    description: 'The historic capital blending ancient monuments like Qutub Minar and Humayun\'s Tomb with contemporary energy and markets.',
    costIndex: 'Moderate',
    popularity: 88,
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 28.7041, lng: 77.1025 },
  },
  {
    name: 'Amritsar',
    country: 'India',
    region: 'Punjab',
    description: 'Spiritual sanctuary of the Golden Temple (Harmandir Sahib), Wagah Border ceremony, and legendary Punjabi kulchas.',
    costIndex: 'Budget',
    popularity: 78,
    image: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 31.634, lng: 74.8723 },
  },
  {
    name: 'Rishikesh & Haridwar',
    country: 'India',
    region: 'Uttarakhand',
    description: 'Yoga Capital of the World along the pristine Ganga, famous for white-water rafting, suspension bridges, and ashrams.',
    costIndex: 'Budget',
    popularity: 75,
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 30.0869, lng: 78.2676 },
  },
  {
    name: 'Shimla',
    country: 'India',
    region: 'Himachal Pradesh',
    description: 'Queen of the Hills, former British summer capital with heritage Mall Road, Christ Church, and UNESCO Toy Train.',
    costIndex: 'Moderate',
    popularity: 73,
    image: 'https://images.unsplash.com/photo-1589802829985-817e51171b92?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 31.1048, lng: 77.1734 },
  },
  {
    name: 'Srinagar & Gulmarg',
    country: 'India',
    region: 'Jammu & Kashmir',
    description: 'Paradise on Earth with Dal Lake Shikara rides, heritage houseboats, Mughal Gardens, and Gulmarg Gondola snow slopes.',
    costIndex: 'Moderate',
    popularity: 81,
    image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 34.0837, lng: 74.7973 },
  },
  {
    name: 'Bengaluru',
    country: 'India',
    region: 'Karnataka',
    description: 'The Garden City and Silicon Valley of India, celebrated for pleasant weather, craft breweries, and Lalbagh botanical gardens.',
    costIndex: 'Moderate',
    popularity: 70,
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 12.9716, lng: 77.5946 },
  },
  {
    name: 'Mysore',
    country: 'India',
    region: 'Karnataka',
    description: 'The Heritage City of Palaces, famous for the illuminated Mysore Palace, Chamundi Hill, sandalwood, and silk.',
    costIndex: 'Budget',
    popularity: 69,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 12.2958, lng: 76.6394 },
  },
  {
    name: 'Alleppey (Alappuzha)',
    country: 'India',
    region: 'Kerala',
    description: 'The Venice of the East, famous for tranquil backwaters, traditional luxury houseboat stays, and palm-fringed lagoons.',
    costIndex: 'Moderate',
    popularity: 77,
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 9.4981, lng: 76.3388 },
  },
  {
    name: 'Wayanad',
    country: 'India',
    region: 'Kerala',
    description: 'Lush Western Ghats sanctuary with prehistoric Edakkal Caves, waterfalls, spice trails, and misty hill hikes.',
    costIndex: 'Budget',
    popularity: 60,
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 11.6854, lng: 76.132 },
  },
  {
    name: 'Hyderabad',
    country: 'India',
    region: 'Telangana',
    description: 'City of Pearls with majestic Charminar, Golconda Fort, pearl markets, and world-renowned Hyderabadi Dum Biryani.',
    costIndex: 'Moderate',
    popularity: 72,
    image: 'https://images.unsplash.com/photo-1605007493699-ce65834f8a00?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 17.385, lng: 78.4867 },
  },
  {
    name: 'Ooty & Nilgiris',
    country: 'India',
    region: 'Tamil Nadu',
    description: 'Picturesque hill station in the Blue Nilgiri Mountains with tea gardens, Pykara Lake, and UNESCO mountain railway.',
    costIndex: 'Moderate',
    popularity: 66,
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 11.4102, lng: 76.695 },
  },
  {
    name: 'Pondicherry',
    country: 'India',
    region: 'Puducherry',
    description: 'Charming French colonial quarter with pastel villas, beachfront promenade cafes, and the spiritual oasis of Auroville.',
    costIndex: 'Budget',
    popularity: 68,
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 11.9416, lng: 79.8083 },
  },
  {
    name: 'Darjeeling',
    country: 'India',
    region: 'West Bengal',
    description: 'Famous for world-class tea estates, majestic views of Mount Kanchenjunga from Tiger Hill, and Himalayan Toy Train.',
    costIndex: 'Moderate',
    popularity: 70,
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 27.041, lng: 88.2663 },
  },
  {
    name: 'Gangtok & Sikkim',
    country: 'India',
    region: 'Sikkim',
    description: 'Clean mountain capital with views of Kanchenjunga, ancient Buddhist monasteries, alpine Tsomgo Lake, and Nathu La Pass.',
    costIndex: 'Moderate',
    popularity: 67,
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 27.3389, lng: 88.6065 },
  },
  {
    name: 'Shillong & Meghalaya',
    country: 'India',
    region: 'Meghalaya',
    description: 'The Scotland of the East, famed for living root bridges, crystal clear Umngot River in Dawki, and cascading waterfalls.',
    costIndex: 'Budget',
    popularity: 71,
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 25.5788, lng: 91.8933 },
  },
  {
    name: 'Andaman & Nicobar Islands',
    country: 'India',
    region: 'Andaman and Nicobar',
    description: 'Tropical paradise featuring world-renowned Radhanagar Beach on Havelock Island, coral reefs, and scuba diving.',
    costIndex: 'Luxury',
    popularity: 78,
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 11.7401, lng: 92.6586 },
  },
  {
    name: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Middle East',
    description: 'Futuristic city featuring Burj Khalifa, desert safaris, ultra-luxury shopping, and marina yacht cruises.',
    costIndex: 'Luxury',
    popularity: 95,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 25.2048, lng: 55.2708 },
  },
  {
    name: 'Singapore',
    country: 'Singapore',
    region: 'Southeast Asia',
    description: 'Vibrant global city with futuristic Gardens by the Bay, Marina Bay Sands, Sentosa Island, and world-class street food.',
    costIndex: 'Luxury',
    popularity: 91,
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1000&q=80',
    coordinates: { lat: 1.3521, lng: 103.8198 },
  },
];

export const seedActivities = [
  // --- UDAIPUR ---
  {
    cityName: 'Udaipur',
    name: 'Lake Pichola Sunset Boat Cruise',
    category: 'sightseeing',
    description: 'Scenic boat ride around Jag Mandir and Lake Palace during golden sunset hours.',
    cost: 800,
    duration: 1.5,
    image: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80',
    popularity: 95,
  },
  {
    cityName: 'Udaipur',
    name: 'City Palace Complex Guided Tour',
    category: 'museum',
    description: 'Explore the royal courtyards, mirror artwork, and history of Mewar dynasty.',
    cost: 450,
    duration: 2.5,
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    popularity: 91,
  },
  {
    cityName: 'Udaipur',
    name: 'Dharohar Folk Dance Show at Bagore Ki Haveli',
    category: 'culture',
    description: 'Enchanting Rajasthani traditional dance, puppet shows, and live music by the lake.',
    cost: 300,
    duration: 1.5,
    image: 'https://images.unsplash.com/photo-1588096344356-9a2c351f506e?auto=format&fit=crop&w=800&q=80',
    popularity: 87,
  },

  // --- JAIPUR ---
  {
    cityName: 'Jaipur',
    name: 'Amer Fort & Sheesh Mahal Tour',
    category: 'sightseeing',
    description: 'Grand hilltop fortress with mirror palace, ancient bastions, and panoramic valley views.',
    cost: 600,
    duration: 3,
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    popularity: 98,
  },
  {
    cityName: 'Jaipur',
    name: 'Nahargarh Fort Sunset & City Viewpoint',
    category: 'nature',
    description: 'Panoramic twilight overlooking the entire pink city from the Aravalli hills.',
    cost: 200,
    duration: 2,
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
    popularity: 88,
  },
  {
    cityName: 'Jaipur',
    name: 'Hot Air Balloon Safari over Jaipur Countryside',
    category: 'adventure',
    description: 'Floating high above ancient palaces, desert villages, and Aravali peaks.',
    cost: 8500,
    duration: 3,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    popularity: 84,
  },

  // --- GOA ---
  {
    cityName: 'Goa',
    name: 'Scuba Diving & Water Sports at Grand Island',
    category: 'adventure',
    description: 'Snorkeling, scuba diving, and banana rides near Grand Island with certified instructors.',
    cost: 2500,
    duration: 5,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    popularity: 94,
  },
  {
    cityName: 'Goa',
    name: 'Fontainhas Latin Quarter Walking Tour',
    category: 'culture',
    description: 'Explore colorful Portuguese heritage villas, art galleries, and quaint cafes in Panaji.',
    cost: 500,
    duration: 2,
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    popularity: 86,
  },
  {
    cityName: 'Goa',
    name: 'Dudhsagar Waterfall Jeep Jungle Safari',
    category: 'nature',
    description: 'Jeep expedition through Mollem National Park to India\'s four-tiered cascading waterfall.',
    cost: 1800,
    duration: 6,
    image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80',
    popularity: 90,
  },

  // --- AGRA ---
  {
    cityName: 'Agra',
    name: 'Sunrise at the Taj Mahal Guided Tour',
    category: 'sightseeing',
    description: 'Witness the iconic white marble wonder glowing in early morning golden light.',
    cost: 750,
    duration: 3,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    popularity: 97,
  },

  // --- VARANASI ---
  {
    cityName: 'Varanasi',
    name: 'Morning Boat Ride & Evening Ganga Aarti',
    category: 'culture',
    description: 'Rowboat experience along historic Dashashwamedh Ghat followed by the mesmerizing lamp ceremony.',
    cost: 500,
    duration: 3,
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
    popularity: 93,
  },

  // --- MANALI ---
  {
    cityName: 'Manali',
    name: 'Solang Valley Paragliding & Adventure',
    category: 'adventure',
    description: 'Tandem paragliding, zorbing, and ropeway rides across snow-capped peaks.',
    cost: 2200,
    duration: 4,
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
    popularity: 89,
  },

  // --- LEH LADAKH ---
  {
    cityName: 'Leh Ladakh',
    name: 'Pangong Lake Day Expedition',
    category: 'nature',
    description: 'High altitude drive through Chang La pass to the mesmerizing blue waters of Pangong Tso.',
    cost: 3500,
    duration: 8,
    image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80',
    popularity: 96,
  },

  // --- KERALA (MUNNAR / ALLEPPEY) ---
  {
    cityName: 'Munnar & Kochi',
    name: 'Kolukkumalai Sunrise Jeep Safari & Tea Factory',
    category: 'nature',
    description: 'Off-road jeep journey to the world\'s highest organic tea estate for sunrise.',
    cost: 1500,
    duration: 4,
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
    popularity: 92,
  },
  {
    cityName: 'Alleppey (Alappuzha)',
    name: 'Backwaters Luxury Houseboat Cruise & Traditional Lunch',
    category: 'sightseeing',
    description: 'Day cruise through serene backwater canals with authentic Kerala sadya meal.',
    cost: 4000,
    duration: 5,
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
    popularity: 93,
  },

  // --- HAMPI ---
  {
    cityName: 'Hampi',
    name: 'Virupaksha Temple & Coracle Boat Ride on Tungabhadra',
    category: 'culture',
    description: 'Explore the 7th-century temple complex and glide on a round basket boat.',
    cost: 600,
    duration: 3,
    image: 'https://images.unsplash.com/photo-1600100397608-f010f4439c71?auto=format&fit=crop&w=800&q=80',
    popularity: 85,
  },

  // --- AMRITSAR ---
  {
    cityName: 'Amritsar',
    name: 'Golden Temple Langar & Wagah Border Ceremony',
    category: 'culture',
    description: 'Volunteer at the world\'s largest community kitchen followed by the iconic retreat parade.',
    cost: 300,
    duration: 5,
    image: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=800&q=80',
    popularity: 94,
  },

  // --- AHMEDABAD ---
  {
    cityName: 'Ahmedabad',
    name: 'Sabarmati Ashram & Heritage Pol Walk',
    category: 'culture',
    description: 'Visit the peaceful residence of Mahatma Gandhi and take a guided morning stroll through historical pols.',
    cost: 400,
    duration: 3,
    image: 'https://images.unsplash.com/photo-1609137144820-ea04e6c1e345?auto=format&fit=crop&w=800&q=80',
    popularity: 81,
  },
  {
    cityName: 'Ahmedabad',
    name: 'Traditional Gujarati Thali Feast at Vishalla',
    category: 'food',
    description: 'Authentic village-themed dining experience with a grand spread of unlimited seasonal Gujarati delicacies.',
    cost: 750,
    duration: 2,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    popularity: 86,
  },

  // --- MUMBAI ---
  {
    cityName: 'Mumbai',
    name: 'Elephanta Caves Ferry & Island Exploration',
    category: 'museum',
    description: 'Ferry ride from Gateway of India to 5th-century rock-cut Shiva sculptures.',
    cost: 700,
    duration: 4,
    image: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?auto=format&fit=crop&w=800&q=80',
    popularity: 88,
  },

  // --- DELHI ---
  {
    cityName: 'Delhi',
    name: 'Old Delhi Street Food & Chandni Chowk Rickshaw Trail',
    category: 'food',
    description: 'Culinary walk tasting Paranthe Wali Gali, kebabs, jalebis, and spiced lassi in historic alleys.',
    cost: 850,
    duration: 3,
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    popularity: 90,
  },

  // --- DUBAI ---
  {
    cityName: 'Dubai',
    name: 'Burj Khalifa At The Top & Dubai Fountain',
    category: 'sightseeing',
    description: 'Access the 124th floor observatory deck for 360-degree views of Dubai skyline.',
    cost: 3800,
    duration: 2,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    popularity: 96,
  },
];
